name: LifeEase
description: A Flutter-based healthcare application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_secure_storage: ^9.2.0
  syncfusion_flutter_charts: ^26.2.9
  agora_rtc_engine: ^6.5.3
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  go_router: ^16.3.0
  intl: ^0.18.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^7.2.0
  intl_phone_number_input: ^0.7.5
  firebase_storage: ^12.4.10
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/